import '../../styles/globals.css'

export const metadata = {
    title: 'TechMath Puzzle App',
    description: 'Generated by Next.js',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html lang='ja'>
            <body>{children}</body>
        </html>
    )
}
